#!/bin/bash
#SBATCH --job-name=tRNA-Seq analysis
#SBATCH -o rnaseq.out
#SBATCH -e rnaseq.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=anujsharma@ufl.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=12GB
#SBATCH --time=18:00:00
#SBATCH --account=gms6231
#SBATCH --qos=gms6231
#SBATCH --workdir=/ufrc/gms6231/share/anujsharma/project/

pwd;hostname;date

# Loading modules
ml tophat/2.1.0
ml cufflinks

# Path for source files
fastq='/ufrc/gms6231/share/Project/RawData'
gene='/ufrc/gms6231/share/Project/RawData/Drosophila_melanogaster/Ensembl/BDGP5.25/Annotation/Genes/genes.gtf'
bowtie='/ufrc/gms6231/share/Project/RawData/Drosophila_melanogaster/Ensembl/BDGP5.25/Sequence/Bowtie2Index'

# Aligning reads with Tophat
tophat -p 8 -G $gene -o ./tophat/C1_R1 $bowtie/genome $fastq/GSM794483_C1_R1_1.fq.gz $fastq/GSM794483_C1_R1_2.fq.gz
tophat -p 8 -G $gene -o ./tophat/C1_R2 $bowtie/genome $fastq/GSM794484_C1_R2_1.fq.gz $fastq/GSM794484_C1_R2_2.fq.gz
tophat -p 8 -G $gene -o ./tophat/C1_R3 $bowtie/genome $fastq/GSM794485_C1_R3_1.fq.gz $fastq/GSM794485_C1_R3_2.fq.gz
tophat -p 8 -G $gene -o ./tophat/C2_R1 $bowtie/genome $fastq/GSM794486_C2_R1_1.fq.gz $fastq/GSM794486_C2_R1_2.fq.gz
tophat -p 8 -G $gene -o ./tophat/C2_R2 $bowtie/genome $fastq/GSM794487_C2_R2_1.fq.gz $fastq/GSM794487_C2_R2_2.fq.gz
tophat -p 8 -G $gene -o ./tophat/C2_R3 $bowtie/genome $fastq/GSM794488_C2_R3_1.fq.gz $fastq/GSM794488_C2_R3_2.fq.gz
wait
echo 'Completed tophat.'; date

# Assemble transcript with Cufflinks
cufflinks -p 8 -o ./cufflinks/C1_R1 ./tophat/C1_R1/accepted_hits.bam
cufflinks -p 8 -o ./cufflinks/C1_R2 ./tophat/C1_R2/accepted_hits.bam 
cufflinks -p 8 -o ./cufflinks/C1_R3 ./tophat/C1_R3/accepted_hits.bam 
cufflinks -p 8 -o ./cufflinks/C2_R1 ./tophat/C2_R1/accepted_hits.bam 
cufflinks -p 8 -o ./cufflinks/C2_R2 ./tophat/C2_R2/accepted_hits.bam 
cufflinks -p 8 -o ./cufflinks/C2_R3 ./tophat/C2_R3/accepted_hits.bam 
wait
echo 'Complete cufflinks.'; date

# Merge transcripts into transcriptome
echo -e './cufflinks/C1_R1/transcripts.gtf\n./cufflinks/C1_R2/transcripts.gtf\n./cufflinks/C1_R3/transcripts.gtf\n./cufflinks/C2_R1/transcripts.gtf\n./cufflinks/C2_R2/transcripts.gtf\n./cufflinks/C2_R3/transcripts.gtf' > assemblies.txt
cuffmerge -o ./assembly -g $gene -s $bowtie/genome.fa -p 8 assemblies.txt
wait
echo 'Complete cuffmerge.'; date

# Find differential expression
cuffdiff -o cuffdiff -b $bowtie/genome.fa -p 8 -L C1,C2 -u ./assembly/merged.gtf \
./tophat/C1_R1/accepted_hits.bam,./tophat/C1_R2/accepted_hits.bam,./tophat/C1_R3/accepted_hits.bam \
./tophat/C2_R1/accepted_hits.bam,./tophat/C2_R2/accepted_hits.bam,./tophat/C2_R3/accepted_hits.bam
wait
echo 'Complete cuffdiff.'; date

# Make expression plot
Rscript expplot.r
wait
echo 'Complete expression plot.'; date

# Index bam files
for i in .tophat/*/accepted_hits.bam; do echo $i; samtools index $i ; done;
for i in .tophat/*/accepted_hits.bam; do echo $i; samtools idxstats $i ; done;
wait
echo 'Complete samtools indexing.'; date

# Compare expression level of genes
find . -name transcripts.gtf > gtflist.txt
cuffcompare -i gtflist.txt -r genes.gtf
wait
echo 'Complete cuffcompare.'; date

# Get transfrag reconstruction statistics
for i in 'find . -name *.tmap'; do echo $i; awk 'NR > 1 { s[$3]++ } END { for (j in s) { print j, s[j] }} ' $i; done;
wait
echo 'Complete transfrag reconstruction.'; date

# Get significantly differentially expressed genes
Rscript diffexp.r
echo 'Complete differential expression script.'; date

echo 'Completed job.'