library(cummeRbund)
cuff_data = readCufflinks('cuffdiff')
gene_diff_data = diffData(genes(cuff_data))
sig_gene_data = subset(gene_diff_data, (significant == 'yes'))
nrow(sig_gene_data)
isoform_diff_data = diffData(isoforms(cuff_data), 'C1', 'C2')
sig_isoform_data = subset(isoform_diff_data, (significant == 'yes'))
nrow(sig_isoform_data)
tss_diff_data = diffData(TSS(cuff_data), 'C1', 'C2')
sig_tss_data = subset(tss_diff_data, (significant == 'yes'))
nrow(sig_tss_data)
cds_diff_data = diffData(CDS(cuff_data), 'C1', 'C2')
sig_cds_data = subset(cds_diff_data, (significant == 'yes'))
nrow(sig_cds_data)
promoter_diff_data = distValues(promoters(cuff_data))
sig_promoter_data = subset(promoter_diff_data, (significant == 'yes'))
nrow(sig_promoter_data)
splicing_diff_data = distValues(splicing(cuff_data))
sig_splicing_data = subset(splicing_diff_data, (significant == 'yes'))
nrow(sig_splicing_data)
relCDS_diff_data = distValues(relCDS(cuff_data))
sig_relCDS_data = subset(relCDS_diff_data, (significant == 'yes'))
nrow(sig_relCDS_data)
gene_diff_data = diffData(genes(cuff_data))
sig_gene_data = subset(gene_diff_data, (significant == 'yes'))
write.table(sig_gene_data, 'diff_genes.txt', sep = '\t', row.names = F, col.names = T, quote = F)