library(cummeRbund)
cuff_data = readCufflinks('cuffdiff')
csDensity(genes(cuff_data))
csScatter(genes(cuff_data), 'C1', 'C2')
csVolcano(genes(cuff_data), 'C1', 'C2')
mygene = getGene(cuff_data,'regucalcin')
expressionBarplot(mygene)
expressionBarplot(isoforms(mygene))
quit()